### ISSUE TITLE
如何在mac m1芯片上编译？

### ISSUE THREAD

**Issue by MyMonsterCat** [RapidAI/OnnxruntimeBuilder#1]

**Comment by benjaminwan** [comment]
官方仓库[Release页面](https://github.com/microsoft/onnxruntime/releases)有提供编译好的
onnxruntime-osx-arm64-版本.tgz
如果想自己编译，需要安装xcode，cmake，git，python，同步官方仓库代码，然后把本仓库的onnxruntime_cmake_options.txt和build-onnxruntime.sh复制到同步好的文件夹里运行。
最后生成的build/MacOS/Release/install是动态库，build/MacOS/Release/install-static是静态库。
