### ISSUE TITLE
请问有支持ubuntu14.04的版本吗？release里找不到1.6.0了

### ISSUE THREAD

**Issue by Sokkafan** [RapidAI/OnnxruntimeBuilder#3]

**Comment by benjaminwan** [comment]
https://github.com/RapidAI/OnnxruntimeBuilder/releases/tag/1.6.0

**Comment by Sokkafan** [comment]
> https://github.com/RapidAI/OnnxruntimeBuilder/releases/tag/1.6.0

非常感谢

**Comment by Sokkafan** [comment]
> https://github.com/RapidAI/OnnxruntimeBuilder/releases/tag/1.6.0

请问有支持32位Ubuntu14.04的吗？这个版本好像只支持64位的

**Comment by benjaminwan** [comment]
32位没有编译。32位的系统太少了，如果有需要后续可以考虑尝试增加。

**Comment by Sokkafan** [comment]
有需求

**Comment by benjaminwan** [comment]
初次尝试编译失败了，似乎是sse指令集方面的编译错误。

**Comment by Sokkafan** [comment]
sse指令集，我尝试在flags.make中添加-msee -msee2之后没再报指令集的问题

**Comment by benjaminwan** [comment]
看了源码，onnxruntime最早的版本就从ubuntu1604开始，所以最终结果是在ubuntu1404上无法编译通过。
